version: '3.8'
services: 
  postgres:
    image: postgres:15
    environment: 
      POSTGRES_USER: task_user
      POSTGRES_PASSWORD: task_password
      POSTGRES_DB: task_database
    ports:
    - "5432:5432"
    volumes:
    - postgres_data:/var/lib/postgresql/data
    - ./db/migratons:/docker-entrypoint-initdb.d

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@taskapi.com
      PGADMIN_DEFAULT_PASSWORD: admin_password

    ports:
    - "8081:80"
    depends_on:
    - postgres

volumes:
  postgres_data: